name: ohtodo
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  responsive_framework: ^1.4.0

  go_router: ^13.2.2
  path_provider: ^2.0.15
  #management
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5
  freezed: ^2.5.0
  equatable: ^2.0.5

  dio: ^5.4.2+1
  fpdart: ^1.1.0
  isar: ^4.0.0-dev.14
  isar_flutter_libs: ^4.0.0-dev.14

  shared_preferences: ^2.2.2

  google_fonts: ^6.2.1
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.6
  flutter_animate: ^4.5.0
  appwrite: ^12.0.1
  logger: ^2.2.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  custom_lint: ^0.6.4
  riverpod_lint: ^2.3.10
  riverpod_generator: ^2.4.0
  flutter_lints: ^3.0.0

  build_runner: ^2.4.9
  json_serializable: ^6.7.1
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

